### ISSUE TITLE
[Admin/Booking V2] Pre-populate remaining plan-derived fields in the schedule-create modal (#1196 follow-up)

### ISSUE THREAD

**Issue by smallwei0301** [smallwei0301/tour-platform#1213]
## Background

PR #1211 (first slice of #1196) taught the Admin schedule-create modal at `apps/web/app/admin/activities/[id]/edit/page.tsx` to pre-seed `capacity` and `minParticipants` from the selected V2 plan. Two more plan-derived fields could give operators the same benefit but weren't shipped in that PR to keep the slice small:

- **`duration_minutes`** — currently the modal asks for `startHH` + `endHH` and the operator has to compute the right end manually. The plan already has a `duration_minutes` value; selecting a plan could auto-update `endHH = startHH + duration_minutes`.
- **`base_price`** — display-only echo would help operators sanity-check they're attaching the schedule to the right plan, especially when ≥2 plans exist and the names are similar (e.g. "半日" vs "半日加長").

## Why this is its own follow-up

These two are pure UX polish on top of #1211's canonical-defaults wiring. They don't change resolver behaviour, schedule contract, or test surface. Bundling them into #1211 would have pulled in:

- A small parser to add minutes to `HH:MM` correctly when the result crosses a day boundary.
- Re-deciding whether `startHH` change re-derives `endHH` or whether the dependency only flows plan → endHH at first seed (UX call: how surprising is auto-updating endHH while the operator is typing?).

Both are real questions; neither is hard, but they need a sketch before code.

## Acceptance criteria

- [ ] Selecting a plan (or auto-applying the single-plan case) seeds `endHH = startHH + plan.duration_minutes`. Operator can still type over it.
- [ ] If the operator changes `startHH` later, `endHH` either follows (option A) OR shows a small "套用方案預設時長" button (option B) — pick one and document the choice in the PR description.
- [ ] Display `base_price` next to the plan dropdown / auto-apply row, e.g. "（每人 NT$ 1,800）". Display-only — no field, no override.
- [ ] No change to the `POST /api/v2/admin/activities/<id>/schedules` body shape — duration is implicit in `startAt`/`endAt`, and the price is a plan attribute, not a schedule attribute.
- [ ] Unit/source-contract test confirming `V2ActivityPlan` interface in the page carries `duration_minutes` + `base_price` (already there) and that the seeding effect references them.
- [ ] No regression in the existing `capacity` / `minParticipants` seeding from #1211.

## Out of scope

- Schedule end-time validation against `plan.max_duration_minutes` (no such field today).
- Changing the schedule contract to carry `duration_minutes` instead of `endAt`.
- Multi-plan bulk-create rewrite (operators currently create one plan's schedule batch at a time; works fine).

## Suggested implementation sketch

```tsx
// In useEffect on planId change (already exists):
if (!selectedPlan) return;
if (selectedPlan.max_participants) setCapacity(String(selectedPlan.max_participants));
if (selectedPlan.min_participants) setMinParticipants(String(selectedPlan.min_participants));
+ if (selectedPlan.duration_minutes) {
+   setEndHH(addMinutesToHHMM(startHH, selectedPlan.duration_minutes));
+ }
```

where `addMinutesToHHMM('09:00', 240) === '13:00'`. Trivially testable; ~10 LoC helper.

## Safety / privacy

- UI polish; no payment/refund/settlement change.
- No new secrets.

## Related

- Parent: #1196 (Booking V2 unified field precedence)
- Shipped first slice: PR #1211
- Sibling follow-up: #1212 (cross-surface visual QA)
- Page: `apps/web/app/admin/activities/[id]/edit/page.tsx` `AddScheduleModal`
- V2 plans API: `apps/web/app/api/v2/admin/activities/[activityId]/plans/route.ts` (already returns `duration_minutes` and `base_price`)
